/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as FilamentosRouteImport } from './routes/filamentos'
import { Route as Impressao3dRouteImport } from './routes/impressao-3d'
import { Route as ImpressorasRouteImport } from './routes/impressoras'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const FilamentosRoute = FilamentosRouteImport.update({
  id: '/filamentos',
  path: '/filamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const Impressao3dRoute = Impressao3dRouteImport.update({
  id: '/impressao-3d',
  path: '/impressao-3d',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressorasRoute = ImpressorasRouteImport.update({
  id: '/impressoras',
  path: '/impressoras',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/filamentos': typeof FilamentosRoute
  '/impressao-3d': typeof Impressao3dRoute
  '/impressoras': typeof ImpressorasRoute
  '/loja': typeof LojaRoute
  '/produto/$slug': typeof ProdutoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/filamentos': typeof FilamentosRoute
  '/impressao-3d': typeof Impressao3dRoute
  '/impressoras': typeof ImpressorasRoute
  '/loja': typeof LojaRoute
  '/produto/$slug': typeof ProdutoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/filamentos': typeof FilamentosRoute
  '/impressao-3d': typeof Impressao3dRoute
  '/impressoras': typeof ImpressorasRoute
  '/loja': typeof LojaRoute
  '/produto/$slug': typeof ProdutoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carrinho'
    | '/checkout'
    | '/filamentos'
    | '/impressao-3d'
    | '/impressoras'
    | '/loja'
    | '/produto/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carrinho'
    | '/checkout'
    | '/filamentos'
    | '/impressao-3d'
    | '/impressoras'
    | '/loja'
    | '/produto/$slug'
  id:
    | '__root__'
    | '/'
    | '/carrinho'
    | '/checkout'
    | '/filamentos'
    | '/impressao-3d'
    | '/impressoras'
    | '/loja'
    | '/produto/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
  FilamentosRoute: typeof FilamentosRoute
  Impressao3dRoute: typeof Impressao3dRoute
  ImpressorasRoute: typeof ImpressorasRoute
  LojaRoute: typeof LojaRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filamentos': {
      id: '/filamentos'
      path: '/filamentos'
      fullPath: '/filamentos'
      preLoaderRoute: typeof FilamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressao-3d': {
      id: '/impressao-3d'
      path: '/impressao-3d'
      fullPath: '/impressao-3d'
      preLoaderRoute: typeof Impressao3dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressoras': {
      id: '/impressoras'
      path: '/impressoras'
      fullPath: '/impressoras'
      preLoaderRoute: typeof ImpressorasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
  FilamentosRoute: FilamentosRoute,
  Impressao3dRoute: Impressao3dRoute,
  ImpressorasRoute: ImpressorasRoute,
  LojaRoute: LojaRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
